version: "3"
services:
    dockernextjs:
        container_name: "docker-nextjs-application"
        ports:
            - "5000:3000"
        build: .
        volumes:
            - ./:/docker-nextjs-application
            #- ./docker-nextjs-application:/docker-nextjs-application
        image: dexdevlab/docker-nextjs-application