version: "3"
services:
    dockernextjs:
        container_name: "docker-nextjs-application"
        ports:
            - "5000:3000"
        build: .
        image: dexdevlab/docker-nextjs-application