version: "3"
services:
    dockernextjs:
        container_name: "docker-nextjs-application"
        #ports:
           # - "8000:8000"
        build: .
        volumes:
            - .:./files
        image: dexdevlab/docker-nextjs-application